paginate: 10
paginate_path: "page:num"

plugins:
  - jekyll-paginate
  - jekyll-feed
kmarkdown: redcarpet


# 作者信息
author: 
  name: loneqd
  email: alonelsj@gmail.com
  link: 

# 站点信息
title: loneqd的博客
description: loneqd的博客
url: 
rss_url: /pages/atom.xml

# gavatar头像及Favicon
gavatar: /public/img/logo.jpg
favicon: /public/img/logo.jpg

# Google Analytics
google_analytics: UA-32679694-2

# 主题设置，自动激活某个标签
active: 技术


# 中文本地化
locals:
  tags: 标签
  about: 关于
  newest: 最新文章
  archive: 归档
 