permalink: /:year/:month/:day/:title.html
paginate: 10
plugins: [jekyll-paginate]
kmarkdown: redcarpet


# 作者信息
author: 
  name: 拍大师
  email: longshujun@aipai.com
  link: http://aipai.com

# 站点信息
title: 拍大师的文档中心
description: 拍大师的文档中心
url: http://192.168.40.8:4000/index.html
rss_url: /pages/atom.xml


# gavatar头像及Favicon
gavatar: /public/img/logo.jpg
favicon: /public/img/logo.jpg

# google analytics 设置
ga:
  id: UA-54262064-1 
  url: painterlin.com

# disqus 设置
disqus:
  shortname: painterlin
  

# 主题设置，自动激活某个标签
active: 技术

# 首页除了最新文章外显示分类
cates: 
  - Optimization
  - LaTeX

# 中文本地化
locals:
  tags: 标签
  about: 关于
  newest: 最新文章
  archive: 归档
 